# Generated by Django 4.1.1 on 2022-09-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "post_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("by", models.CharField(max_length=50)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("post_type", models.CharField(max_length=50)),
                ("url", models.URLField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
