# Generated by Django 4.1.1 on 2022-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_base_id_alter_base_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="base",
            name="post_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
