# Generated by Django 4.1.1 on 2022-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_base_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="base",
            name="id",
        ),
        migrations.AlterField(
            model_name="base",
            name="post_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
