# Generated by Django 4.1.1 on 2022-09-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_base_id_alter_base_post_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="base",
            name="kids",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "comment_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("by", models.CharField(max_length=50)),
                ("text", models.TextField(blank=True, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("comment_type", models.CharField(max_length=50)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.base"
                    ),
                ),
            ],
        ),
    ]
