# Generated by Django 4.1.1 on 2022-09-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_base_kids_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.IntegerField(),
        ),
    ]
